### ISSUE TITLE
Function name displayed in .pdb files

### ISSUE THREAD

**Issue by HongThatCong** [hasherezade/tiny_tracer#39]
Pin v3.28, tiny_tracer v2.6
I don't know if this is new code of tiny_tracer or new feature of Pin v3.28.
When the environment variable _NT_SYMBOL_PATH is set, and I have long since set it, the tiny_tracer (or Pin v3.28) will path and display the function name according to the debug symbol files (.pdb/.xxx).
So the functions I define in params.txt don't match.
I was forced to delete (temporarily rename) this _NT_SYMBOL_PATH environment variable.
Previous versions of Pin and tiny_tracer do not have this problem.
Below is a screenshot of an example.
![image](https://github.com/hasherezade/tiny_tracer/assets/67528122/c02e9773-116b-468c-b8e4-79f6c533b2ee)
And after turn off _NT_SYMBOL_PATH, it run OK
![image](https://github.com/hasherezade/tiny_tracer/assets/67528122/a29ecc21-669d-4156-9749-90e58eac7101)

**Comment by hasherezade** [comment]
hi @HongThatCong !
Thanks for reporting. I didn't change anything related with the name resolutions in TinyTracer, so I believe this is a change introduced in Pin platform itself.
I will investigate it in details soon, and make some workaround.
Can you try to compile the current tracer with Pin 3.26 and let me know if the same problem occurs?

**Comment by hasherezade** [comment]
@HongThatCong - please check if my latest commit helps. For now I disabled using Debug symbols at all, only export symbols (so it should work like if the `_NT_SYMBOL_PATH` was not available).
Later I am gonna implement a version with demangling.

**Comment by hasherezade** [comment]
@HongThatCong - I also implemented name unmangling in a new branch: https://github.com/hasherezade/tiny_tracer/tree/unmangle
Please try both options and let me know if they help.

**Comment by HongThatCong** [comment]
Somethings still wrong with unmangling branch.
1. An underscore in front of the output name has been removed (by PIN_UndecorateSymbolName func?)
![image](https://github.com/hasherezade/tiny_tracer/assets/67528122/57dc5c4c-3737-4a25-8053-a5aa2ccf6146)

2. Function name still get from debug symbol name (pdb).
![image](https://github.com/hasherezade/tiny_tracer/assets/67528122/71cb4000-1778-44e2-82f6-11028b613f3b)

3. But C++ export demangled is OK
![image](https://github.com/hasherezade/tiny_tracer/assets/67528122/416fbe91-ad18-4a50-b0e3-1cdb864367b7)

**Comment by hasherezade** [comment]
@HongThatCong  - thanks for checking.
Unfortunately, when some functions are represented by different names in the Debug symbol vs Exports, it is gonna be difficult to solve. Pin doesn't offer any way of using both versions simultaneously. And there is no one way to normalize them.
What I can do is making it configurable via [INI file](https://github.com/hasherezade/tiny_tracer/wiki/The-INI-file), whether or not you want the Debug symbols to be used.

**Comment by hasherezade** [comment]
@HongThatCong - please check the update to the [unmangle](https://github.com/hasherezade/tiny_tracer/tree/unmangle) branch.
Now you can select if from the INI file if you want to use the debug symbols: https://github.com/hasherezade/tiny_tracer/blob/unmangle/install32_64/TinyTracer.ini#L2
